In [22]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Activation

In [23]:
import numpy as np
data = np.random.random((20, 100))
labels = np.random.randint(3, size=(20, 1))
x_test = np.random.random((5,100))
y_test = np.array([[1],[1],[1],[0],[0]])
# Train the model, iterating on the data in batches of 32 samples




In [24]:
labels

array([[1],
       [2],
       [2],
       [1],
       [1],
       [0],
       [1],
       [0],
       [2],
       [0],
       [2],
       [1],
       [2],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0]])

In [52]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=100))
model.add(Dense(16, activation='relu',input_dim=33))
model.add(Dense(3, activation='softmax'))
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [53]:
one_hot_labels = keras.utils.to_categorical(labels, num_classes=3)

In [54]:
one_hot_labels

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.]])

In [55]:
#model.fit(data, labels, epochs=10, batch_size=15)
model.fit(data, one_hot_labels, epochs=10, batch_size=15)

Epoch 1/10
20/20 [==============================] - 0s - loss: 0.6454 - acc: 0.6667     
Epoch 2/10
20/20 [==============================] - 0s - loss: 0.6254 - acc: 0.6667     
Epoch 3/10
20/20 [==============================] - 0s - loss: 0.6164 - acc: 0.6667     
Epoch 4/10
20/20 [==============================] - 0s - loss: 0.6119 - acc: 0.6667     
Epoch 5/10
20/20 [==============================] - 0s - loss: 0.6022 - acc: 0.6667     
Epoch 6/10
20/20 [==============================] - 0s - loss: 0.5941 - acc: 0.6667     
Epoch 7/10
20/20 [==============================] - 0s - loss: 0.5856 - acc: 0.6667     
Epoch 8/10
20/20 [==============================] - 0s - loss: 0.5816 - acc: 0.6667     
Epoch 9/10
20/20 [==============================] - 0s - loss: 0.5761 - acc: 0.7000     
Epoch 10/10
20/20 [==============================] - 0s - loss: 0.5738 - acc: 0.7000     


In [56]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_29 (Dense)             (None, 32)                3232      
_________________________________________________________________
dense_30 (Dense)             (None, 16)                528       
_________________________________________________________________
dense_31 (Dense)             (None, 3)                 51        
Total params: 3,811
Trainable params: 3,811
Non-trainable params: 0
_________________________________________________________________


In [30]:
score = model.evaluate(x_test, y_test, batch_size=15,verbose=1)

5/5 [==============================] - 0s


In [31]:
y_pred = model.predict(x_test)

In [32]:
np.mean(y_test == y_pred)

0.0

In [19]:
y_test

array([[1],
       [1],
       [0],
       [1],
       [0]])

In [20]:
y_pred

array([[ 0.87735981],
       [ 0.62964523],
       [ 0.92412388],
       [ 0.80112118],
       [ 0.88168401]], dtype=float32)

In [52]:
b = y_pred < 0.60

In [53]:
b

array([[ True],
       [False],
       [False],
       [False],
       [ True]], dtype=bool)

In [54]:
y_pred[b] = 0

In [55]:
y_pred

array([[ 0.        ],
       [ 0.7079522 ],
       [ 0.69020808],
       [ 0.66364312],
       [ 0.        ]], dtype=float32)

In [58]:
b = y_pred > 0

In [59]:
b

array([[False],
       [ True],
       [ True],
       [ True],
       [False]], dtype=bool)

In [60]:
y_pred[b] = 1

In [61]:
np.mean(y_test == y_pred)

0.59999999999999998