In [1]:
# The objective of the this Test Case Predictor BOTS is to trigger Test Case based on source code changes. 
# The code is divided into parts
# Machine Learning - First Part
# This learns a given set of mapped 'source to test case / scenario' dataset 
# Once the training the set is learned, the KNN machine learning algorithm will implement AI to map  
# source code to any new Test Cases written
# 
# Dev Ops - Second Part
# Scan the input source code changes to find the test case that needs to be executed

# Imports machine learning and matrix handling python libraries
import os  
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier

In [4]:
# Reads the ';' separted training(initial) file into a Panda Dataframe
os.chdir(r'E:\MachineLearning\Python\Text Learning')
path = os.getcwd() + r'\ex1data2.txt'
data = pd.read_csv(path, header=None,sep = ';', names=['Function', 'TC']) 

In [5]:
# prints the first five of dataframe to show that how data got loaded
print(data.head())

  Function                              TC
0  Contact      Verify Creation of Contact
1  Contact      Verify Updating of Contact
2  Contact      Verify Deletion of Contact
3  Contact  Change the Account of Contacts
4  Contact            Verify Contact Lists


In [6]:
# Transform the dataframe into labels & features
X = data.Function.tolist()
y = data.TC.tolist()

In [7]:
# Instantiate count vectorizer for extracting featues
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()

In [8]:
# Fit the feature vector
vect.fit(y)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [9]:
# Display Extracted Key Words 
vect.get_feature_names()

['account',
 'activate',
 'admin',
 'and',
 'change',
 'contact',
 'contacts',
 'contract',
 'core',
 'creation',
 'deletion',
 'display',
 'duplicate',
 'edit',
 'in',
 'lists',
 'mass',
 'merge',
 'of',
 'run',
 'stay',
 'the',
 'touch',
 'update',
 'updating',
 'verify']

In [10]:
# Transform the feature into text data matrix 
simple_train_dty = vect.transform(y)


In [9]:
simple_train_dty

<13x26 sparse matrix of type '<class 'numpy.int64'>'
	with 52 stored elements in Compressed Sparse Row format>

In [11]:
datain = simple_train_dty.toarray()

In [12]:
# Converted text data into numbers
datain

array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
        1, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 

In [13]:
# Converted test case text into integers
pd.DataFrame(simple_train_dty.toarray(),columns=vect.get_feature_names())

account  activate  admin  and  change  contact  contacts  contract  core  \
0         0         0      0    0       0        1         0         0     0   
1         0         0      0    0       0        1         0         0     0   
2         0         0      0    0       0        1         0         0     0   
3         1         0      0    0       1        0         1         0     0   
4         0         0      0    0       0        1         0         0     0   
5         0         0      0    0       0        0         1         0     0   
6         0         0      1    0       0        0         0         0     1   
7         0         0      0    0       0        0         0         0     0   
8         0         0      0    0       0        0         0         1     0   
9         0         0      0    0       0        0         0         1     0   
10        0         0      0    0       0        0         0         1     0   
11        0         0      0    1       0        0         0         1     0   
12        0         1      0    0       0        0         0         1     0   

    creation   ...    mass  merge  of  run  stay  the  touch  update  \
0          1   ...       0      0   1    0     0    0      0       0   
1          0   ...       0      0   1    0     0    0      0       0   
2          0   ...       0      0   1    0     0    0      0       0   
3          0   ...       0      0   1    0     0    1      0       0   
4          0   ...       0      0   0    0     0    0      0       0   
5          0   ...       0      1   0    0     0    0      0       0   
6          0   ...       0      0   0    1     0    0      0       0   
7          0   ...       1      0   0    0     1    1      1       1   
8          1   ...       0      0   1    0     0    0      0       0   
9          0   ...       0      0   1    0     0    0      0       0   
10         0   ...       0      0   1    0     0    0      0       0   
11         0   ...       0      0   1    0     0    0      0       0   
12         0   ...       0      0   0    0     0    0      0       0   

    updating  verify  
0          0       1  
1          1       1  
2          0       1  
3          0       0  
4          0       1  
5          0       0  
6          0       0  
7          0       1  
8          0       1  
9          1       1  
10         0       1  
11         0       0  
12         0       0  

[13 rows x 26 columns]

In [14]:
vect1 = CountVectorizer()
vect1.fit(X)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [15]:
opfeat = vect1.get_feature_names()

In [16]:
simple_train_dtX = vect1.transform(X)

In [17]:
dataop = simple_train_dtX.toarray()

In [18]:
# Converted source code text into label integers
dataop

array([[0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]], dtype=int64)

In [20]:
rows = dataop.shape[0]
cols = dataop.shape[1]

In [21]:
op = np.zeros((rows,), dtype=np.int64)

In [22]:
for i in range(rows):
    s = 0
    for j in range(cols):
        s = s + dataop[i,j] * (j + 1)
    op[i] =op[i] + s
print(op)

[2 2 2 2 2 2 1 2 3 3 3 3 3]


In [23]:
# Building KNN model to learn the training set
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(simple_train_dty, op)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [24]:
# Tester Writes a new Test Scenario for a project
simple_test = ["search of contract"]
#vect = CountVectorizer()

In [26]:
# converts new test case into integer
simple_test_dtm = vect.transform(simple_test)
simple_test_dtm.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0]], dtype=int64)

In [27]:
#pd.DataFrame(simple_test_dtm.toarray(),columns=vect.get_feature_names())

In [28]:
# predicts the source code
knn.predict(simple_test_dtm)

array([3], dtype=int64)

In [29]:
pred = knn.predict(simple_test_dtm)[0]

In [30]:
def uniq(input):
  output = []
  for x in input:
    if x not in output:
      output.append(x)
  return output

In [31]:
opremdup = uniq(op.tolist())

In [32]:
print(opfeat[pred - 1])
print(''.join(simple_test))

contract
search of contract


In [33]:
# Maps the learned test case to new source code and adds to training set
try:
    f = open(path, 'a')
    try:
       wr = str(opfeat[pred - 1]) + ';' + ''.join(simple_test)
       f.write('\n' + wr) # Write a string to a file
     #   f.writelines(lines) # Write a sequence of strings to a file
    finally:
        f.close()
except IOError:
    pass


In [34]:
# source code chnaged for product
code_changed = ['Admin', 'Contract']

In [35]:
try:
    with open(path) as f:
        content = f.read().splitlines()
except IOError:
    pass

In [36]:
# Implements Devops to find the test case to be executed
for codeelem in code_changed:
    #print ('codeelem' + codeelem)
    for element in content:
        element = element.lower()
        #print ('element' + element)
        parts = element.split(';')
        if codeelem.lower() in parts:
            print('Execute the testcase: ' + parts[1])
    

Execute the testcase: run core admin
Execute the testcase: verify creation of contract
Execute the testcase: verify updating of contract
Execute the testcase: verify deletion of contract
Execute the testcase: display and edit of contract
Execute the testcase: activate contract
Execute the testcase: search of contract
